FROM node
LABEL Ezequiel F
#RUN mkdir /home/app
#RUN npm install --global npm@3.7.5
EXPOSE 8080
#HOME = Variável de ambiente
ENV HOME=/home/app
#COPY package.json  $HOME/dezconto-site/

WORKDIR $HOME/dezconto-site/
#VOLUME $HOME/dezconto-site/

#RUN npm install
#RUN npm install --silent --progess=false

#COPY . $HOME/dezconto-site


